chore(deps): update dependency https://github.com/dafyddj/copier-salt-winrepo to v1.5.23

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,7 @@ on:
   - workflow_dispatch
 
 env:
-  REPO_JSON_DIR: repo_data
+  REPO_JSON_ARTIFACT: repo_data
   REPO_JSON_FILE: repo.json
 
 jobs:
@@ -15,7 +15,7 @@ jobs:
     name: Should run
     permissions:
       pull-requests: read
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     timeout-minutes: 5
     outputs:
       should-run: ${{ steps.action.outputs.should-run }}
@@ -26,12 +26,12 @@ jobs:
     name: Run `pre-commit`
     needs: should-run
     if: fromJSON(needs.should-run.outputs.should-run)
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     env:
       # renovate: datasource=custom.python-versions depName=actions/python-versions versioning=pep440
-      PYTHON_VERSION: 3.13.5
+      PYTHON_VERSION: 3.13.7
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
@@ -40,18 +40,18 @@ jobs:
     name: Get Salt versions
     needs: should-run
     if: fromJSON(needs.should-run.outputs.should-run)
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     outputs:
       salt-versions-els: ${{ steps.get-salt-versions.outputs.salt-versions-els }}
       salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
       salt-latest: ${{ steps.get-salt-versions.outputs.salt-latest }}
     steps:
       - id: get-salt-versions
-        uses: dafyddj/get-salt-versions@ac257a534c1352d2456c7e795e4c60705cb44378 # v3.4.7
+        uses: dafyddj/get-salt-versions@0aaf87b67c2f9ab9eb9a17e72684f7fee86e5ad8 # v3.4.9
   refresh_db:
     name: Test `pkg.refresh_db`
     needs: gsv
-    runs-on: windows-latest
+    runs-on: windows-2025
     strategy:
       fail-fast: false
       matrix:
@@ -59,7 +59,7 @@ jobs:
           - ${{ fromJSON(needs.gsv.outputs.salt-versions-els) }}
           - ${{ fromJSON(needs.gsv.outputs.salt-versions) }}
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
         with:
           path: win/repo-ng
       - name: Setup Salt
@@ -92,7 +92,7 @@ jobs:
         if: needs.gsv.outputs.salt-latest == matrix.salt-version
         with:
           if-no-files-found: error
-          name: ${{ env.REPO_JSON_DIR }}
+          name: ${{ env.REPO_JSON_ARTIFACT }}
           path: ${{ env.REPO_JSON_FILE }}
           retention-days: 10
   test:
@@ -102,9 +102,9 @@ jobs:
     permissions:
       contents: read
       pull-requests: read
-    runs-on: windows-latest
+    runs-on: windows-2025
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       - id: changed-files
         name: Get changed files
         uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
@@ -138,33 +138,36 @@ jobs:
       issues: write
       pull-requests: write
       checks: read
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
         with:
           ignore: Collect results
           token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
         with:
           sparse-checkout: |
             .cicd/
             .releaserc.cjs
       - id: sem-rel
-        uses: codfish/semantic-release-action@b621d34fabe0940f031e89b6ebfea28322892a10 # v3.5.0
+        uses: codfish/semantic-release-action@22ce451ffd02a9ee2c4bfd126d028e4bd655770e # v4.0.0
         with:
           additional-packages: conventional-changelog-conventionalcommits@7.0.2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
         if: runner.debug || fromJSON(steps.sem-rel.outputs.new-release-published)
       - name: Transform dumped repo data to Renovate-style JSON
         if: runner.debug || fromJSON(steps.sem-rel.outputs.new-release-published)
         run: |
-          if [ -f "$REPO_JSON_DIR/$REPO_JSON_FILE" ]; then
-            .cicd/transform-json < "$REPO_JSON_DIR/$REPO_JSON_FILE"
+          if [ -f "$REPO_JSON_FILE" ]; then
+            .cicd/transform-json < "$REPO_JSON_FILE"
             echo "::group::Display resulting directory structure"
             ls --almost-all --recursive --ignore node_modules --ignore .git
             echo "::endgroup::"
+          else
+            echo "::error ::Data file '$REPO_JSON_FILE' not found."
+            exit 1
           fi
       - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
         if: fromJSON(steps.sem-rel.outputs.new-release-published)
